// AUTH
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

// CLASSES
export const CLASSES_FETCH_SUCCESS = 'CLASSES_FETCH_SUCCESS';
export const CLASSES_FETCH_REQUEST = 'CLASSES_FETCH_REQUEST';
export const CLASSES_FETCH_FAILURE = 'CLASSES_FETCH_FAILURE';

export const ADDCLASS_SUCCESS = 'ADDCLASS_SUCCESS';
export const ADDCLASS_REQUEST = 'ADDCLASS_REQUEST';
export const ADDCLASS_FAILURE = 'ADDCLASS_FAILURE';


// STUDENT
export const ADDSTUDENT_REQUEST = 'ADDSTUDENT_REQUEST';
export const ADDSTUDENT_SUCCESS = 'ADDSTUDENT_SUCCESS';
export const ADDSTUDENT_FAILURE = 'ADDSTUDENT_FAILURE';

// ASSIGNMENT
export const ADDASSIGNMENT_SUCCESS = 'ADDASSIGNMENT_SUCCESS';
export const ADDASSIGNMENT_REQUEST = 'ADDASSIGNMENT_REQUEST';
export const ADDASSIGNMENT_FAILURE = 'ADDASSIGNMENT_FAILURE';

export const ADD_USER = 'ADD_USER';


export const EDIT_CLASS = 'EDIT_CLASS';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const EDIT_ASSIGNMENT = 'EDIT_ASSIGNMENT';
export const DELETE_CLASS = 'DELETE_CLASS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';